[package]
name = "compax-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "cx"
path = "src/main.rs"
#required-features = ["cli"]

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
tar = "0.4.44"
zstd = "0.13.3"